@startuml As-Is Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(admin, "Администратор", "Сотрудник компании 'Теплый дом'", "Подключение системы отопления Клиента к системе")
Person(customer, "Клиент", "Владелец системы отопления", "Управляет отоплением в доме, проверяет температуру")

System(system, "Система 'Умный дом'", "Позволяет удаленно управлять отоплением в доме")

System_Ext(heating_device, "Отопительное оборудование", "Аппаратное устройство", "Управляет температурой в помещении")
System_Ext(temperature_sensor, "Датчик температуры", "Аппаратное устройство", "Измеряет текущую температуру")

Rel(admin, system, "Настраивает систему\nПодключает отопительное оборудование")
Rel(customer, system, "Включает\выключает отопление\nПросматривает температуру")
Rel(system, heating_device, "Включает/выключает\nрегулирует температуру")
Rel(system, temperature_sensor, "Опрашивает текущую\nтемпературу")

@enduml