openapi: 3.1.0
info:
  title: Heating Service API
  version: 1.1.0
paths:
  /heating-devices:
    post:
      summary: Зарегистрировать отопительное устройство
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HeatingCreate'
      responses:
        '201':
          description: Устройство зарегистрировано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Heating'
    get:
      summary: Получить список отопительных устройств по дому
      parameters:
        - name: homeId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Список устройств
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Heating'

  /heating-devices/{deviceId}:
    get:
      summary: Получить информацию об устройстве
      parameters:
        - name: deviceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Данные устройства
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Heating'
    delete:
      summary: Удалить устройство
      parameters:
        - name: deviceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Устройство удалено

components:
  schemas:
    HeatingCreate:
      type: object
      required: [homeId]
      properties:
        homeId:
          type: string
        temperatureTarget:
          type: number
    Heating:
      allOf:
        - $ref: '#/components/schemas/HeatingCreate'
        - type: object
          properties:
            id:
              type: string
            temperatureCurrent:
              type: number
